# Part A

### Q1 - Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
list = [x for x in range(1, 21, 3)]
print(list)

[1, 4, 7, 10, 13, 16, 19]


In [3]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


'f:\conestoga\ai' is not recognized as an internal or external command,
operable program or batch file.


###  Q2 - Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
import numpy as np

list2 = np.random.rand(3)

print(list2)
print(list2.shape)

[0.63804512 0.67069126 0.70654224]
(3,)


### Q3 - Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] 

In [5]:


td_array = np.array([[10,20,45], [30,12,16], [42,17,56]])

print ("Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.")


first_two_rows = td_array[:2,:]

last_two_rows = td_array[1:,:]


print(f"first two rows : {first_two_rows}")
print(f"last two rows : {last_two_rows}")

Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
first two rows : [[10 20 45]
 [30 12 16]]
last two rows : [[30 12 16]
 [42 17 56]]


### Q4 - Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [6]:
first_array = np.array([[42,17],[30,12]])
second_array = np.array([[20,45],[13,16]])


verticle_stack = np.vstack((first_array,second_array))

horizontal_stack = np.hstack((first_array,second_array))

print(f"verticlly stacked arrays : {verticle_stack}")

print(f"horizontally stacked arrays : {horizontal_stack}")



split_first_array_ver = np.vsplit(first_array,2)

split_first_array_hor = np.hsplit(first_array,2)


print(f"verticlly split arrays : {split_first_array_ver}")
print(f"horizontally split arrays : {split_first_array_hor}")




verticlly stacked arrays : [[42 17]
 [30 12]
 [20 45]
 [13 16]]
horizontally stacked arrays : [[42 17 20 45]
 [30 12 13 16]]
verticlly split arrays : [array([[42, 17]]), array([[30, 12]])]
horizontally split arrays : [array([[42],
       [30]]), array([[17],
       [12]])]


### Q5 - Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
#### Is it possible to multiply these matrices?
#### Demonstrate the case when it is not possible to.

In [7]:
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y= np.array([[4, 2], [6, 2], [4, 2]])

print(f"shape of X: {X.shape}")
print(f"shape of Y: {Y.shape}")



shape of X: (3, 3)
shape of Y: (3, 2)


In [8]:
demo_X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
demo_Y = np.array([[4, 2], [6, 2]])
try:
    multi = np.dot(demo_X, demo_Y)
except Exception as e:
    print(e)

shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Q6 - Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
#### Find the Shape, Number of dimensions of vector x.
#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [9]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

shape_x = x.shape
dim_x = x.ndim

print(f"shape of x  is  : {shape_x} and dimension of x is {dim_x}")

x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))

print(f"shape of reshaped x  is  : {x_reshaped.shape} and dimension of reshaped x is {x_reshaped.ndim} \n reshaped x {x_reshaped}")

print(f"shape of reshaped y  is  : {y_reshaped.shape} and dimension of reshaped y is {y_reshaped.ndim}\n reshaped y {y_reshaped}")



shape of x  is  : (3,) and dimension of x is 1
shape of reshaped x  is  : (3, 1) and dimension of reshaped x is 2 
 reshaped x [[ 2]
 [-1]
 [-8]]
shape of reshaped y  is  : (3, 1) and dimension of reshaped y is 2
 reshaped y [[ 3]
 [ 1]
 [-2]]


### How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.


Broadcasting in NumPy allows us to perform different operations on arrays without re-shaping them. When there's difference in shape, broadcasting handles it by maximizing the smaller array to the shape of larger one.

In example below, 
broadcasting is demonstrated by doing substraction and multiplication on 3*3 matrix. It allowed us to multiply the matrix by the number 6 and substract the same matix by number 5. It automatically took care of difference of shape between the matrix and number 6 and 5 respectively while performing those arithmetic operations. 

In [10]:
my_matr = np.random.rand(3, 3)

print(f"The 3*3 matirx : \n {my_matr}")

sub_matr = my_matr - 5
print(f"Matrix after substration : \n {sub_matr}")


mul_matr = my_matr * 6

print(f"Matrix after multiplication :\n {mul_matr}")



The 3*3 matirx : 
 [[0.3261808  0.08063159 0.48720569]
 [0.00942024 0.67388485 0.98784733]
 [0.50711876 0.26521671 0.35078603]]
Matrix after substration : 
 [[-4.6738192  -4.91936841 -4.51279431]
 [-4.99057976 -4.32611515 -4.01215267]
 [-4.49288124 -4.73478329 -4.64921397]]
Matrix after multiplication :
 [[1.95708479 0.48378955 2.92323415]
 [0.05652145 4.04330911 5.92708397]
 [3.04271254 1.59130023 2.10471618]]


# Part B

## Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.

### Part B.1

In [11]:
cooff = np.array([[4, 1, -2],[2, -3, 2],[1, 2, 3]])

constant = np.array([10, -4, 6])

determinant = np.linalg.det(cooff)

print(determinant)

-70.00000000000003


To determine the singularity, linalg function from numpy is used. 
As seen from the result, the determinant is non zero number, which tells that the matrix is non-singular. The solution is found using solve function from linalg.

In [12]:
sol = np.linalg.solve(cooff, constant)
print(sol)

[ 1.8  2.4 -0.2]


### Part B.2

In [13]:
cooff_b = np.array([[2, -1, 3, 4],[4, -2, 6, 8],[3, 1, -2, 2],[1, 3, -4, 1]])

constant_b = np.array([10, 20, 3, -1])

determinant_b = np.linalg.det(cooff_b)
print(determinant_b)

0.0


Here, in this case, we can see the deteminant value is zero, which suggests that the matrix is singular and would not be possible to find a solution, as it could have no solution or infinite solutions. 

In [14]:
from numpy.linalg import LinAlgError
try:
    sol_b = np.linalg.solve(cooff_b, constant_b)
except LinAlgError as e:
    print("The system is already singular and might not have a unique solution.")

The system is already singular and might not have a unique solution.
