### Q1 - Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [19]:
list = [x for x in range(1, 21, 3)]
print(list)

[1, 4, 7, 10, 13, 16, 19]


In [4]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


'f:\conestoga\ai' is not recognized as an internal or external command,
operable program or batch file.


###  Q2 - Create a new array of shape 3 with random numbers between 0 and 1.

In [20]:
import numpy as np

list2 = np.random.rand(3)

print(list2)
print(list2.shape)

[0.71376457 0.3323655  0.49696122]
(3,)


### Q3 - Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] 

In [21]:


td_array = np.array([[10,20,45], [30,12,16], [42,17,56]])

print ("Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.")


first_two_rows = td_array[:2,:]

last_two_rows = td_array[1:,:]


print(f"first two rows : {first_two_rows}")
print(f"last two rows : {last_two_rows}")

Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
first two rows : [[10 20 45]
 [30 12 16]]
last two rows : [[30 12 16]
 [42 17 56]]


### Q4 - Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [22]:
first_array = np.array([[42,17],[30,12]])
second_array = np.array([[20,45],[13,16]])


verticle_stack = np.vstack((first_array,second_array))

horizontal_stack = np.hstack((first_array,second_array))

print(f"verticlly stacked arrays : {verticle_stack}")

print(f"horizontally stacked arrays : {horizontal_stack}")



split_first_array_ver = np.vsplit(first_array,2)

split_first_array_hor = np.hsplit(first_array,2)


print(f"verticlly split arrays : {split_first_array_ver}")
print(f"horizontally split arrays : {split_first_array_hor}")




verticlly stacked arrays : [[42 17]
 [30 12]
 [20 45]
 [13 16]]
horizontally stacked arrays : [[42 17 20 45]
 [30 12 13 16]]
verticlly split arrays : [array([[42, 17]]), array([[30, 12]])]
horizontally split arrays : [array([[42],
       [30]]), array([[17],
       [12]])]


### Q5 - Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
#### Is it possible to multiply these matrices?
#### Demonstrate the case when it is not possible to.

In [8]:
X= np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y= np.array([[4, 2], [6, 2], [4, 2]])

print(f"shape of X: {X.shape}")
print(f"shape of Y: {Y.shape}")



shape of X: (3, 3)
shape of Y: (3, 2)


In [9]:
demo_X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
demo_Y = np.array([[4, 2], [6, 2]])
try:
    multi = np.dot(demo_X, demo_Y)
except Exception as e:
    print(e)

shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Q6 - Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
#### Find the Shape, Number of dimensions of vector x.
#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [10]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

shape_x = x.shape
dim_x = x.ndim

print(f"shape of x  is  : {shape_x} and dimension of x is {dim_x}")

x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))

print(f"shape of reshaped x  is  : {x_reshaped.shape} and dimension of reshaped x is {x_reshaped.ndim} \n reshaped x {x_reshaped}")

print(f"shape of reshaped y  is  : {y_reshaped.shape} and dimension of reshaped y is {y_reshaped.ndim}\n reshaped y {y_reshaped}")



shape of x  is  : (3,) and dimension of x is 1
shape of reshaped x  is  : (3, 1) and dimension of reshaped x is 2 
 reshaped x [[ 2]
 [-1]
 [-8]]
shape of reshaped y  is  : (3, 1) and dimension of reshaped y is 2
 reshaped y [[ 3]
 [ 1]
 [-2]]


### How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.


Broadcasting in NumPy allows us to perform different operations on arrays without re-shaping them. When there's difference in shape, broadcasting handles it by maximizing the smaller array to the shape of larger one.

In example below, 
broadcasting is demonstrated by doing substraction and multiplication on 3*3 matrix. It allowed us to multiply the matrix by the number 6 and substract the same matix by number 5. It automatically took care of difference of shape between the matrix and number 6 and 5 respectively while performing those arithmetic operations. 

In [23]:
my_matr = np.random.rand(3, 3)

print(f"The 3*3 matirx : \n {my_matr}")

sub_matr = my_matr - 5
print(f"Matrix after substration : \n {sub_matr}")


mul_matr = my_matr * 6

print(f"Matrix after multiplication :\n {mul_matr}")



The 3*3 matirx : 
 [[0.13935805 0.39130303 0.98179792]
 [0.1589155  0.88611104 0.60318977]
 [0.9500035  0.6633018  0.64601085]]
Matrix after substration : 
 [[-4.86064195 -4.60869697 -4.01820208]
 [-4.8410845  -4.11388896 -4.39681023]
 [-4.0499965  -4.3366982  -4.35398915]]
Matrix after multiplication :
 [[0.83614828 2.3478182  5.89078755]
 [0.95349297 5.31666623 3.61913863]
 [5.70002099 3.97981083 3.87606509]]
