In [8]:
print ("Q1 - Create an array that starts from the integer 1, ends at 20, incremented by 3.")
list = [x for x in range(1, 21, 3)]
print(list)

Q1 - Create an array that starts from the integer 1, ends at 20, incremented by 3.
[1, 4, 7, 10, 13, 16, 19]


In [2]:
%pip install numpy


     ---------------------------------------- 15.5/15.5 MB 4.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
print ("Q2 - Create a new array of shape 3 with random numbers between 0 and 1.")

import numpy as np

list2 = np.random.rand(3)

print(list2)
print(list2.shape)

Q2 - Create a new array of shape 3 with random numbers between 0 and 1.
[0.80399923 0.60279146 0.1100465 ]
(3,)


In [10]:
print ("Q3 - Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] ")


td_array = np.array([[10,20,45], [30,12,16], [42,17,56]])

print ("Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.")


first_two_rows = td_array[:2,:]

last_two_rows = td_array[1:,:]


print(f"first two rows : {first_two_rows}")
print(f"last two rows : {last_two_rows}")

Q3 - Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] 
Q3(a) - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
first two rows : [[10 20 45]
 [30 12 16]]
last two rows : [[30 12 16]
 [42 17 56]]


In [15]:
print ("Q4 - Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.")



first_array = np.array([[42,17],[30,12]])
second_array = np.array([[20,45],[13,16]])


verticle_stack = np.vstack((first_array,second_array))

horizontal_stack = np.hstack((first_array,second_array))

print(f"verticlly stacked arrays : {verticle_stack}")

print(f"horizontally stacked arrays : {horizontal_stack}")



split_first_array_ver = np.vsplit(first_array,2)

split_first_array_hor = np.hsplit(first_array,2)


print(f"verticlly split arrays : {split_first_array_ver}")
print(f"horizontally split arrays : {split_first_array_hor}")




Q4 - Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
verticlly stacked arrays : [[42 17]
 [30 12]
 [20 45]
 [13 16]]
horizontally stacked arrays : [[42 17 20 45]
 [30 12 13 16]]
verticlly split arrays : [array([[42, 17]]), array([[30, 12]])]
horizontally split arrays : [array([[42],
       [30]]), array([[17],
       [12]])]
